### ISSUE TITLE
Display of versions/versionOf and parts/partOf for individual DOIs

### ISSUE THREAD

**Issue by mfenner** [datacite/akita#13]
Using the GraphQL API.

```
    versions(first:5){
      nodes{
        publicationYear
        version
        doi
      }
    }
    parts(first: 5) {
      nodes {
        publicationYear
        version
        doi
      }
    }
```

**Comment by kjgarza** [comment]
On this one, I think we need to narrow down what the user story and the wireframe of the list (how do we want this to look like).

is the user story?

**As a** researcher
**I want** to be able to see a list with all the versions of a given work   (versions or form part of)  ???
**So that** I can ????????

is there a user story about this somewhere?

**Comment by richardhallett** [comment]
This is stale and closing as probably falls under product enhancement.
