### ISSUE TITLE
PID Graph KPI for DataCite Commons

### ISSUE THREAD

**Issue by mfenner** [datacite/akita#135]
Provide overview page(s) about relevant KPI for the PID Graph in DataCite Commons. This should at least include the number of resources and connections over time, as much as this information is available (e.g. ror and orcid might not exist over time in an API).

**Comment by sarala** [comment]
Initial feedback:

1. General page is good. May be 'Overview' instead of 'General'
2. Navigation could be improved. May be links from the 'Overview' page to different pages would work better. 
3. It would be useful to simplify Publication, Datasets, Software, People and Organisations pages. May be focus on the key message you are trying to get across with a bit more description. I think it makes sense to focus on Citations and Connections over the years.

I think it would make sense for us to spend more time on these aggregations to figure out what exactly we want to communicate here in the coming weeks.

**Comment by mfenner** [comment]
@sarala I have addressed your feedback. Let me know whether this now passes the validation.

**Comment by sarala** [comment]
@mfenner, this is what I have come up with so far.

On the overview page, can we have two subsections with some graphs

1. Connections
- Works connected to people
- Works connected to organisation
- Publications connected to datasets

2. Cited (if needed for freya)
- Cited publications over time
- Cited datasets over time
- Cited software over years

Do you think this would be sufficient for Freya? Then we can remove the additional pages and keep just one overview page.

**Comment by sarala** [comment]
Thanks for all the changes. This looks fine to me.
